const shifts=['08:00 - 17:30','09:00 - 18:30','10:00 - 19:30','12:00 - 21:30','14:00 - 23:30','21:00 - 06:30','23:00 - 08:30','OFF','PH','VL','SL'];
let team=[],schedule={},days=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function monday(){const d=new Date(),n=d.getDay()||7;d.setDate(d.getDate()-n+1);return d.toISOString().slice(0,10)}
function buildDays(){const start=new Date($('#weekStart').value+'T00:00:00');days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return{date:d.toISOString().slice(0,10),occupancy:50,arrivals:0,departures:0,groups:0,remarks:''}});renderForecast()}
function renderForecast(){const labels=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#forecastGrid').innerHTML=days.map((d,i)=>{const date=new Date(d.date+'T00:00:00');return `<div class="day-card"><h3>${labels[date.getDay()]} · ${date.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}</h3>${['occupancy','arrivals','departures','groups'].map(k=>`<label>${k[0].toUpperCase()+k.slice(1)}${k==='occupancy'?' %':''}<input type="number" min="0" data-day="${i}" data-key="${k}" value="${d[k]}"></label>`).join('')}<label>Remarks<input data-day="${i}" data-key="remarks" value="${esc(d.remarks)}"></label></div>`}).join('');$$('[data-day]').forEach(x=>x.oninput=()=>days[+x.dataset.day][x.dataset.key]=x.type==='number'?+x.value:x.value)}
function payload(){return{weekStart:$('#weekStart').value,team,days,schedule}}
async function load(){team=await fetch('/api/team').then(r=>r.json());const saved=localStorage.getItem('ciel-roster-team');if(saved){const map=Object.fromEntries(JSON.parse(saved).map(x=>[x.id,x]));team=team.map(x=>({...x,...map[x.id]}))}renderTeam();updateCounters()}
function renderTeam(){ $('#teamTable').innerHTML=`<thead><tr><th>Name</th><th>Department</th><th>Employee ID</th><th>Preferred shift</th><th>Pending OFF</th><th>Pending PH</th><th>Active</th></tr></thead><tbody>${team.map((p,i)=>`<tr class="${p.active?'':'inactive'}"><td>${esc(p.name)}</td><td>${esc(p.department)}</td><td>${esc(p.employeeId)}</td><td><select data-person="${i}" data-field="preferred">${shifts.filter(x=>!['PH','VL','SL'].includes(x)).map(x=>`<option ${x===p.preferred?'selected':''}>${x}</option>`).join('')}</select></td><td><input class="balance" type="number" min="0" data-person="${i}" data-field="pendingOff" value="${p.pendingOff}"></td><td><input class="balance" type="number" min="0" data-person="${i}" data-field="pendingPH" value="${p.pendingPH}"></td><td><input type="checkbox" data-person="${i}" data-field="active" ${p.active?'checked':''}></td></tr>`).join('')}</tbody>`;$$('[data-person]').forEach(x=>x.onchange=()=>{const p=team[+x.dataset.person];p[x.dataset.field]=x.type==='checkbox'?x.checked:(x.type==='number'?+x.value:x.value);localStorage.setItem('ciel-roster-team',JSON.stringify(team));renderTeam();updateCounters()})}
function cls(v){if(v==='OFF')return'off';if(['PH','VL','SL'].includes(v))return'off';const h=+(v.match(/^\d+/)||[12])[0];return h>=19||h<5?'night':h<11?'morning':'evening'}
function isConflict(prev,cur){return cls(prev)==='night'&&cls(cur)==='morning'}
function renderRoster(){const active=team.filter(x=>x.active);$('#rosterTable').innerHTML=`<thead><tr><th>Team member</th><th>Department</th>${days.map(d=>`<th>${new Date(d.date+'T00:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'2-digit'})}</th>`).join('')}<th>OFF</th><th>Pending OFF</th><th>Pending PH</th></tr></thead><tbody>${active.map(p=>{const row=schedule[p.id]||Array(7).fill('OFF');return`<tr><td>${esc(p.name)}</td><td>${esc(p.department)}</td>${row.map((v,i)=>`<td class="shift-${cls(v)} ${i&&isConflict(row[i-1],v)?'conflict':''}"><select data-shift="${p.id}" data-index="${i}">${shifts.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></td>`).join('')}<td>${row.filter(x=>x==='OFF').length}</td><td>${p.pendingOff}</td><td>${p.pendingPH}</td></tr>`}).join('')}</tbody>`;$$('[data-shift]').forEach(x=>x.onchange=()=>{schedule[x.dataset.shift][+x.dataset.index]=x.value;renderRoster();updateCounters()});updateCounters()}
function updateCounters(){const active=team.filter(x=>x.active);$('#activeCount').textContent=active.length;$('#pendingOff').textContent=active.reduce((a,x)=>a+(+x.pendingOff||0),0);$('#pendingPH').textContent=active.reduce((a,x)=>a+(+x.pendingPH||0),0);$('#offCount').textContent=Object.values(schedule).flat().filter(x=>x==='OFF').length||'–';let alerts=0;Object.values(schedule).forEach(r=>r.forEach((v,i)=>{if(i&&isConflict(r[i-1],v))alerts++}));$('#alerts').textContent=alerts}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#generate').onclick=async()=>{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())}).then(x=>x.json());schedule=r.schedule;renderRoster();toast('Roster generated — review and adjust any shift')};
$('#export').onclick=async()=>{if(!Object.keys(schedule).length)return toast('Generate the roster first');const r=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())}).then(x=>x.json());location.href=r.url;toast('Excel roster created')};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});
$('#weekStart').value=monday();$('#weekStart').onchange=buildDays;buildDays();load();
